-- Migration: add signup fields to User
BEGIN;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "signupType" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "place" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "approved" BOOLEAN DEFAULT false NOT NULL;

COMMIT;
